[project]
name = "portport"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "cffi==2.1.1",
    "cryptography>=50.0.0",
    "prometheus_client==0.26.0",
    "pycparser==3.0"
]

[build-system]
requires=["setuptools>=40.8.0"]
build-backend = "setuptools.build_meta"

[project.scripts]
portport-client = "portport.client.cli:main"
portport-server = "portport.server.cli:main"